#!/bin/sh -e

CONFIG=/etc/schwinn810.conf

if [ x"$1" = x"purge" ]; then
    test -x /usr/bin/ucfr && ucfr --force --purge schwinn810 $CONFIG
    test -x /usr/bin/ucf && ucf --purge $CONFIG
    rm -f $CONFIG
fi

#DEBHELPER#
