#!/bin/sh

	/usr/bin/python3.2 \
	/home/mlt/workspace/schwinn810/src/download.py \
	--debug \
	--port /dev/schwinn810 \
	--dir /home/mlt/Documents/My\ Runs \
	--hook /home/mlt/workspace/schwinn810/src/babelize.sh 
#	--port /dev/schwinn810 \
#	--hook /home/mlt/workspace/schwinn810/src/babelize.sh \
#	--port schwinn810.bin \

