#!/bin/sh

. /etc/schwinn810.conf

[[ $HOOK ]] && HOOK="--hook $HOOK"
[[ $DEBUG ]] && DEBUG="--debug"
YEAR=$(date +%Y)
umask 0002
mkdir -p 2775 $DIR/$YEAR
#mkdir -p -m ug=rwx,o=rx $DIR/$YEAR

/usr/share/schwinn810/download.py $DEBUG $HOOK \
    --port $PORT \
    --dir $DIR/$YEAR && \
[[ $NOTIFY ]] && notify-send -u low -c transfer.complete "Schwinn 810 GPS watch" "Data extracted"
