#!/bin/sh

. /etc/schwinn810.conf

if test -r "$HOME/.schwinn810.conf"
then
    . ~/.schwinn810.conf
fi

HOOK=${HOOK:+--hook $HOOK}
DEBUG=${DEBUG:+--debug}

YEAR=$(date +%Y)
umask 0002
mkdir -p -m 2775 "$DIR/$YEAR"

/usr/share/schwinn810/download.py $DEBUG $HOOK \
    --port $PORT \
    --progress gtk \
    --read-settings \
    --dir "$DIR/$YEAR" && \
[ "$NOTIFY" ] && notify-send -u low -c transfer.complete "Schwinn 810 GPS watch" "Data extracted"
