#!/bin/sh

. /etc/schwinn810.conf

if [[ $NOTIFY ]]; then
    LINES=$(find /proc/ -maxdepth 2 -name environ -exec /usr/share/schwinn810/env.awk {} \; | sort -u)
    for line in $LINES; do
	eval $line
	XAUTHORITY=$XAUTHORITY DISPLAY=$DISPLAY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS notify-send -u low -c device.added "Schwinn 810 GPS watch connected"
    done;
fi

[[ $AUTO ]] || exit

sleep 2				# delay for watch to initialize
/usr/bin/schwinn810 &> /dev/null 

if [[ $RET = 0 && $NOTIFY ]]; then
    for line in $LINES; do
	eval $line
	XAUTHORITY=$XAUTHORITY DISPLAY=$DISPLAY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS notify-send -u low -c device.added "Schwinn 810 GPS watch" "Data extracted"
    done;
fi
